[main]
# Carga zsh de forma predeterminada
shell=/bin/zsh

# Fuente limpia
font=JetBrains Mono:size=6.8

# Margen interno pequeño para que el texto no toque el borde
pad=12x12

[csd]
# Desactiva las barras de titulo y decoraciones (Estilo minimalista puro)
preferred=none

[colors-dark]
# Colores basados en tu paleta "Suave y Ergonómica".
background=1e222a
foreground=abb2bf

# El color "surface" y selección de tu nueva paleta
selection-background=3e4451
selection-foreground=abb2bf

# Paleta base ANSI
regular0=1e222a  # Negro (Fondo)
regular1=e06c75  # Rojo (Coral suave)
regular2=7ec7a2  # Verde (Menta)
regular3=d19a66  # Amarillo (Ámbar suave)
regular4=7aa2f7  # Azul (Azul pastel)
regular5=c678dd  # Magenta (Púrpura/Magenta)
regular6=56b6c2  # Cian (Cian suave)
regular7=abb2bf  # Blanco (Texto principal)

# Variantes brillantes
bright0=5c6370   # Gris
bright1=e06c75   # Rojo
bright2=7ec7a2   # Verde
bright3=d19a66   # Amarillo
bright4=7aa2f7   # Azul
bright5=c678dd   # Magenta
bright6=56b6c2   # Cian
bright7=abb2bf   # Blanco brillante
