general {
    lock_cmd = pidof hyprlock || hyprlock          # Evita abrir múltiples instancias de hyprlock
    before_sleep_cmd = loginctl lock-session      # Bloquea la sesión automáticamente antes de suspender
    after_sleep_cmd = hyprctl dispatch dpms on    # Enciende la pantalla al despertar
}

# Bloquear pantalla tras 20 minutos (1200 segundos)
listener {
    timeout = 1200
    on-timeout = loginctl lock-session
}

listener {
    timeout = 1260
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
