[main]
# Carga zsh de forma predeterminada
shell=/bin/zsh

# Fuente limpia
font=JetBrains Mono:size=6.5

# Margen interno pequeño para que el texto no toque el borde
pad=12x12

[csd]
# Desactiva las barras de titulo y decoraciones (Estilo minimalista puro)
preferred=none

[colors-dark]
# Colores basados en tu configuracion.
background=1e1e2e
foreground=cdd6f4

# El color "surface" funciona perfecto para resaltar texto seleccionado
selection-background=313244
selection-foreground=cdd6f4

# Paleta base ANSI
regular0=1e1e2e  # Negro (Fondo)
regular1=f38ba8  # Rojo
regular2=a6e3a1  # Verde
regular3=f9e2af  # Amarillo
regular4=89b4fa  # Azul (Tu color activo)
regular5=f5c2e7  # Magenta
regular6=94e2d5  # Cian
regular7=cdd6f4  # Blanco (Tu texto)

# Variantes brillantes
bright0=585b70   # Gris
bright1=f38ba8
bright2=a6e3a1
bright3=f9e2af
bright4=89b4fa
bright5=f5c2e7
bright6=94e2d5
bright7=bac2de
